
const CODE_AUTHEN = '001';

const CODE_RASP_INFO = '002';

const CODE_REQUEST_RASP_INFO = '100';

const CODE_REQUEST_OPEN_DOOR = '110';

const CODE_REQUEST_CLOSE_DOOR = '111';

const CODE_REQUEST_LOCK_DOOR = '112';

const CODE_REQUEST_UNLOCK_DOOR = '113';

const CODE_REQUEST_TAKE_PICTURE = '120';

const CODE_REQUEST_WRITE_CARD = '130';

const CODE_CHECK_PERMISION_CARD = '300';

const CODE_SUCCESS = '200';

const CODE_ERROR = '500';

const MESSAGE_SUCCESS = 'SUCCESS';

module.exports = {
  CODE_AUTHEN,
  CODE_REQUEST_CLOSE_DOOR,
  CODE_ERROR,
  CODE_REQUEST_LOCK_DOOR,
  CODE_REQUEST_OPEN_DOOR,
  CODE_RASP_INFO,
  CODE_CHECK_PERMISION_CARD,
  CODE_REQUEST_RASP_INFO,
  CODE_REQUEST_TAKE_PICTURE,
  CODE_REQUEST_WRITE_CARD,
  CODE_SUCCESS,
  MESSAGE_SUCCESS,
  CODE_REQUEST_UNLOCK_DOOR
}

